/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.EcoSystem.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Organization.ResidentOrganization;
import Business.Resident.Resident;
import Business.Resident.ResidentDirectory;
import Business.Street.StreetDirectory;
import Business.UserAccount.UserAccount;
import Business.Validation.Validation;
import UserInterface.Resident.ResidentSignUpJPanel;
import java.awt.CardLayout;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Priyank
 */
public class LoginJPanel extends javax.swing.JPanel {

    private EcoSystem ecoSystem;
    private JPanel userProcessContainer;
    private JButton logoutJButton;
    private ResidentDirectory residentDirectory;
    private Resident resident;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private ResidentOrganization residentOrganization;
    private OrganizationDirectory organizationDirectory;
    private Organization organization;
    private StreetDirectory streetDirectory;
    private Validation validation;

    /**
     * Creates new form loginPanel
     */
    public LoginJPanel(EcoSystem ecoSystem, JPanel userProcessContainer, JButton logoutJButton) {
        initComponents();
        this.ecoSystem = ecoSystem;
        this.userProcessContainer = userProcessContainer;
        this.logoutJButton = logoutJButton;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usernameJTextField = new javax.swing.JTextField();
        loginJButton = new javax.swing.JButton();
        pwdJPasswordField = new javax.swing.JPasswordField();
        residentSignUpJLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username");

        usernameJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameJTextFieldFocusLost(evt);
            }
        });
        usernameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameJTextFieldActionPerformed(evt);
            }
        });

        loginJButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        loginJButton.setText("Login");
        loginJButton.setBorder(null);
        loginJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJButtonActionPerformed(evt);
            }
        });

        pwdJPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwdJPasswordFieldFocusLost(evt);
            }
        });

        residentSignUpJLabel.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        residentSignUpJLabel.setText("Please Click Here to Sign Up!");
        residentSignUpJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                residentSignUpJLabelMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel6.setText("Sign in");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(243, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(pwdJPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(usernameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(335, 335, 335))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(356, 356, 356))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(residentSignUpJLabel)
                        .addGap(301, 301, 301))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pwdJPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(loginJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(residentSignUpJLabel)
                .addContainerGap(115, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void usernameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameJTextFieldActionPerformed

    private void loginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButtonActionPerformed

        if (!Validation.isEmpty(usernameJTextField) || !Validation.isEmpty(pwdJPasswordField)) {
            JOptionPane.showMessageDialog(null, "Highlighted fields are mandatory. Please fill them.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String userName = usernameJTextField.getText();
            char[] passwordCharArray = pwdJPasswordField.getPassword();
            String password = String.valueOf(passwordCharArray);

            Enterprise inEnterprise = null;
            Organization inOrganization = null;

            UserAccount userAccount = ecoSystem.getUserAccountDirectory().authenticateUser(userName, password);
            if (userAccount == null) {
                //Get each network from ecosystem
                for (Network network : ecoSystem.getNetworkList()) {
                    //checking for each enterprise

                    for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {

                        userAccount = enterprise.getUserAccountDirectory().authenticateUser(userName, password);
                        if (userAccount == null) {

                            //checking in the organization
                            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {

                                userAccount = organization.getUserAccountDirectory().authenticateUser(userName, password);

                                if (userAccount != null) {
                                    inEnterprise = enterprise;
                                    inOrganization = organization;
                                    break;
                                }

                            }
                        } else {
                            inEnterprise = enterprise;
                            break;
                        }

                        if (inOrganization != null) {
                            break;
                        }

                    }
                    if (inEnterprise != null) {
                        break;
                    }

                }

            }

            if (userAccount == null) {
                JOptionPane.showMessageDialog(null, "Invalid Credential");
                usernameJTextField.setText("");
                pwdJPasswordField.setText("");
                return;
            } else {
                CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
                userProcessContainer.add("WorkArea", userAccount.getRole().createWorkArea(userProcessContainer, userAccount, inOrganization, inEnterprise, ecoSystem));
                cardLayout.next(userProcessContainer);
                logoutJButton.setVisible(true);
            }

            //loginJButton.setEnabled(false);
            usernameJTextField.setEnabled(false);
            pwdJPasswordField.setEnabled(false);
        }
    }//GEN-LAST:event_loginJButtonActionPerformed

    private void residentSignUpJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_residentSignUpJLabelMouseClicked
        //enterprise.getOrganizationDirectory().getOrganizationList()
        enterprise = ecoSystem.getNetworkList().get(0).getEnterpriseDirectory().getEnterpriseList().get(0);
        ResidentSignUpJPanel rsu = new ResidentSignUpJPanel(userProcessContainer, userAccount, organization, enterprise, ecoSystem, streetDirectory);
        userProcessContainer.add("Resident Sign Up", rsu);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_residentSignUpJLabelMouseClicked

    private void usernameJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameJTextFieldFocusLost
        Validation.isEmptyFieldOnFocusLost(evt);
    }//GEN-LAST:event_usernameJTextFieldFocusLost

    private void pwdJPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdJPasswordFieldFocusLost
        Validation.isEmptyFieldOnFocusLost(evt);
    }//GEN-LAST:event_pwdJPasswordFieldFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton loginJButton;
    private javax.swing.JPasswordField pwdJPasswordField;
    private javax.swing.JLabel residentSignUpJLabel;
    private javax.swing.JTextField usernameJTextField;
    // End of variables declaration//GEN-END:variables
}
