/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Engineer;

import Business.AirQuality.AirIndex;
import Business.EcoSystem.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Message.MessageUtility;
import Business.Organization.EngineerOrganization;
import Business.Organization.Organization;
import Business.Sensor.Sensor;
import Business.Street.Street;
import Business.UserAccount.UserAccount;
import com.teamdev.jxbrowser.chromium.Browser;
import com.teamdev.jxbrowser.chromium.swing.BrowserView;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.io.File;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Priyank
 */
public class SearchSensorLocationJPanel extends javax.swing.JPanel {

    public static final int MIN_ZOOM = 0;
    public static final int MAX_ZOOM = 21;
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private EngineerOrganization engineerOrganization;
    private Enterprise enterprise;
    private EcoSystem ecoSystem;
    final Browser browser;
    private Street street;

    /**
     * Creates new form SearchSensorLocationJPanel
     */
    public SearchSensorLocationJPanel(JPanel userProcessContainer, UserAccount userAccount, EngineerOrganization engineerOrganization, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.engineerOrganization = engineerOrganization;
        this.enterprise = enterprise;
        this.ecoSystem = ecoSystem;

        browser = new Browser();
        BrowserView browserView = new BrowserView(browser);
        //browser.loadURL("C:\\Users\\priya\\Desktop\\thenewboston\\FitBitCity\\map.html");
        File myFile = new File("map.html");
        System.out.println(myFile.getAbsolutePath());
        browser.loadURL(myFile.getAbsolutePath());
        mapPanel.add(browserView, BorderLayout.CENTER);
        revalidate();
        repaint();

        street = userAccount.getStreetLocation();
        streetJTextField.setText(String.valueOf(street));
        populateCombo();
    }

    public void populateCombo() {
        sensorNameJComboBox.removeAllItems();
        for (Sensor sensor : street.getSensorDirectory().getSensorList()) {
            sensorNameJComboBox.addItem(sensor);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        checkJButton = new javax.swing.JButton();
        mapPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        streetJTextField = new javax.swing.JTextField();
        sendLocationJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();
        sensorNameJComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel3.setText("Search Street");

        checkJButton.setText("Get Location");
        checkJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkJButtonActionPerformed(evt);
            }
        });

        mapPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mapPanel.setPreferredSize(new java.awt.Dimension(600, 500));
        mapPanel.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Street");

        streetJTextField.setEnabled(false);

        sendLocationJButton.setText("Send Location");
        sendLocationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendLocationJButtonActionPerformed(evt);
            }
        });

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Sensor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(backJButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sendLocationJButton))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(streetJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(sensorNameJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(checkJButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(refreshJButton))
                        .addComponent(mapPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(253, 253, 253)))
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(streetJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(checkJButton)
                    .addComponent(sensorNameJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(refreshJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mapPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(sendLocationJButton))
                .addContainerGap(140, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkJButtonActionPerformed
        actionPerformed(evt);
    }//GEN-LAST:event_checkJButtonActionPerformed

    private void sendLocationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendLocationJButtonActionPerformed
        if (userAccount.getStreetLocation().getSensorDirectory().getSensorList().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The street has no sensors installed currently.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Sensor sensor = (Sensor) sensorNameJComboBox.getSelectedItem();
            String latitude = String.valueOf(sensor.getLatitude());
            String longitude = String.valueOf(sensor.getLongitude());
            UserAccount ua = null;
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof EngineerOrganization) {
                    ua = organization.getUserAccountDirectory().searchUser(street);
                }
            }

            String phNum = ua.getEmployee().getPhoneNumber();
            MessageUtility.sendLocation(phNum, "The Street co-ordinates you requested has", latitude, longitude);
            JOptionPane.showMessageDialog(null, "Message sent", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_sendLocationJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        EngineerWorkAreaJPanel ewa = (EngineerWorkAreaJPanel) component;
        ewa.populateOfficialRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        refreshPerformed(evt);
    }//GEN-LAST:event_refreshJButtonActionPerformed

//    public void setWaypoint() {
//        Set<Waypoint> waypoints = new HashSet<Waypoint>();
//        Street street = userAccount.getStreetLocation();
//        for (Sensor sensors : street.getSensorDirectory().getSensorList()) {           
//                double latitude = sensors.getLatitude();
//                double longitude = sensors.getLongitude();
//                waypoints.add(new Waypoint(latitude, longitude));
//                WaypointPainter painter = new WaypointPainter();
//                painter.setWaypoints(waypoints);
//                jXMapKit.getMainMap().setOverlayPainter(painter);
//            
//       }
//    }
    public void refreshPerformed(ActionEvent e) {
        browser.executeJavaScript("var myLatlng = new google.maps.LatLng(42.3000, -71.8000);\n"
                + "var marker = new google.maps.Marker({\n"
                + "    position: myLatlng,\n"
                + "    map: map,\n"
                + "    title: 'Massachusetts'\n"
                + "});");
    }

    public void actionPerformed(ActionEvent e) {
        Sensor sensor = (Sensor) sensorNameJComboBox.getSelectedItem();
        String latitude = String.valueOf(sensor.getLatitude());
        String longitude = String.valueOf(sensor.getLongitude());
        int pos = sensor.getAirIndexDirectory().getAirIndexList().size();
        AirIndex airIndex = sensor.getAirIndexDirectory().getAirIndexList().get(pos - 1);
        String result = airIndex.getResult();
        //if(result.toString().equalsIgnoreCase("Good")){
        browser.executeJavaScript("var myLatlng = new google.maps.LatLng(" + latitude + "," + longitude + ");\n"
                + "var marker = new google.maps.Marker({\n"
                //+ "    icon:'http://maps.google.com/mapfiles/ms/icons/green-dot.png',\n"
                + "    position: myLatlng,\n"
                + "    map: map,\n"
                + "    animation: google.maps.Animation.DROP,\n"
                + "    title: '" + result + "',\n"
                + "});");

//        else if(result.toString().equalsIgnoreCase("Moderate")){
//        browser.executeJavaScript("var myLatlng = new google.maps.LatLng("+latitude+","+longitude+");\n"
//                + "var marker = new google.maps.Marker({\n"
//                + "    icon:'http://maps.google.com/mapfiles/ms/icons/yellow-dot.png',\n"
//                + "    position: myLatlng,\n"
//                + "    map: map,\n"
//                + "    animation: google.maps.Animation.DROP,\n"
//                + "    title: '"+result+"',\n"
//                + "});");
//        }
//        else if(result.toString().equalsIgnoreCase("Unhealthy for Sensitive Groups")){
//        browser.executeJavaScript("var myLatlng = new google.maps.LatLng("+latitude+","+longitude+");\n"
//                + "var marker = new google.maps.Marker({\n"
//                + "    icon:'http://maps.google.com/mapfiles/ms/icons/blue-dot.png',\n"
//                + "    position: myLatlng,\n"
//                + "    map: map,\n"
//                + "    animation: google.maps.Animation.DROP,\n"
//                + "    title: '"+result+"',\n"
//                + "});");
//        }
//        else if(result.toString().equalsIgnoreCase("Unhealthy")){
//        browser.executeJavaScript("var myLatlng = new google.maps.LatLng("+latitude+","+longitude+");\n"
//                + "var marker = new google.maps.Marker({\n"
//                + "    icon:'http://maps.google.com/mapfiles/ms/icons/blue-dot.png',\n"
//                + "    position: myLatlng,\n"
//                + "    map: map,\n"
//                + "    animation: google.maps.Animation.DROP,\n"
//                + "    title: '"+result+"',\n"
//                + "});");
//        }
//        else if(result.toString().equalsIgnoreCase("Very Unhealthy")){
//        browser.executeJavaScript("var myLatlng = new google.maps.LatLng("+latitude+","+longitude+");\n"
//                + "var marker = new google.maps.Marker({\n"
//                + "    icon:'http://maps.google.com/mapfiles/ms/icons/red-dot.png',\n"
//                + "    position: myLatlng,\n"
//                + "    map: map,\n"
//                + "    animation: google.maps.Animation.DROP,\n"
//                + "    title: '"+result+"',\n"
//                + "});");
//        }
//        else if(result.toString().equalsIgnoreCase("Hazardous")){
//        browser.executeJavaScript("var myLatlng = new google.maps.LatLng("+latitude+","+longitude+");\n"
//                + "var marker = new google.maps.Marker({\n"
//                + "    icon:'http://maps.google.com/mapfiles/ms/icons/red-dot.png',\n"
//                + "    position: myLatlng,\n"
//                + "    map: map,\n"
//                + "    animation: google.maps.Animation.DROP,\n"
//                + "    title: '"+result+"',\n"
//                + "});");
//        }
//        else if(result.toString().equalsIgnoreCase("Very Hazardous")){
//        browser.executeJavaScript("var myLatlng = new google.maps.LatLng("+latitude+","+longitude+");\n"
//                + "var marker = new google.maps.Marker({\n"
//                + "    icon: BitmapDescriptorFactory.defaultMarker(BitmapDescriptorFactory.HUE_ROSE),\n"
//                + "    position: myLatlng,\n"
//                + "    map: map,\n"
//                + "    animation: google.maps.Animation.DROP,\n"
//                + "    title: '"+result+"',\n"
//                + "});");
//        }
//        if (streetJTextField.getText().equals("Allston")) {
//            if (sensorNameJComboBox.getSelectedItem().toString().equalsIgnoreCase("Sensor 1")) {
//                browser.executeJavaScript("var myLatlng = new google.maps.LatLng(42.353904, -71.133711);\n"
//                        + "var marker = new google.maps.Marker({\n"
//                        + "    position: myLatlng,\n"
//                        + "    map: map,\n"
//                        + "    animation: google.maps.Animation.DROP,\n"
//                        + "    title:+ 'Poor Air Quality',\n"
//                        //+ "    snippet: 'Allston',\n "
//                        + "});");
//            }
//            if (sensorNameJComboBox.getSelectedItem().toString().equalsIgnoreCase("Sensor 2")) {
//                browser.executeJavaScript("var myLatlng = new google.maps.LatLng(42.354661, -71.134697);\n"
//                        + "var marker = new google.maps.Marker({\n"
//                        + "    position: myLatlng,\n"
//                        + "    map: map,\n"
//                        + "    animation: google.maps.Animation.DROP,\n"
//                        + "    title: 'Poor Air Quality',\n"
//                        //+ "    snippet: 'Allston',\n "
//                        + "});");
//            }
//            if (sensorNameJComboBox.getSelectedItem().toString().equalsIgnoreCase("Sensor 3")) {
//                browser.executeJavaScript("var myLatlng = new google.maps.LatLng(42.354538, -71.132685);\n"
//                        + "var marker = new google.maps.Marker({\n"
//                        + "    position: myLatlng,\n"
//                        + "    map: map,\n"
//                        + "    animation: google.maps.Animation.DROP,\n"
//                        + "    title: 'Poor Air Quality',\n"
//                        //+ "    snippet: 'Allston',\n "
//                        + "});");
//            }
//        } else if (streetJTextField.getText().equals("Brighton")) {
//            if (sensorNameJComboBox.getSelectedItem().toString().equalsIgnoreCase("Sensor 1")) {
//                browser.executeJavaScript("var myLatlng = new google.maps.LatLng(42.346350, -71.162676);\n"
//                        + "var marker = new google.maps.Marker({\n"
//                        + "    position: myLatlng,\n"
//                        + "    map: map,\n"
//                        + "    animation: google.maps.Animation.DROP,\n"
//                        + "    title: 'Poor Air Quality'\n"
//                        + "});");
//            }
//            if (sensorNameJComboBox.getSelectedItem().toString().equalsIgnoreCase("Sensor 2")) {
//                browser.executeJavaScript("var myLatlng = new google.maps.LatLng(42.346034, -71.160950);\n"
//                        + "var marker = new google.maps.Marker({\n"
//                        + "    position: myLatlng,\n"
//                        + "    map: map,\n"
//                        + "    animation: google.maps.Animation.DROP,\n"
//                        + "    title: 'Poor Air Quality'\n"
//                        + "});");
//            }
//            if (sensorNameJComboBox.getSelectedItem().toString().equalsIgnoreCase("Sensor 3")) {
//                browser.executeJavaScript("var myLatlng = new google.maps.LatLng(42.347380, --71.161423);\n"
//                        + "var marker = new google.maps.Marker({\n"
//                        + "    position: myLatlng,\n"
//                        + "    map: map,\n"
//                        + "    animation: google.maps.Animation.DROP,\n"
//                        + "    title: 'Poor Air Quality'\n"
//                        + "});");
//            }
//        } else if (streetJTextField.getText().equals("Back-Bay")) {
//            if (sensorNameJComboBox.getSelectedItem().toString().equalsIgnoreCase("Sensor 1")) {
//                browser.executeJavaScript("var myLatlng = new google.maps.LatLng(42.350265, -71.080976);\n"
//                        + "var marker = new google.maps.Marker({\n"
//                        + "    position: myLatlng,\n"
//                        + "    map: map,\n"
//                        + "    animation: google.maps.Animation.DROP,\n"
//                        + "    title: 'Poor Air Quality'\n"
//                        + "});");
//            }
//            if (sensorNameJComboBox.getSelectedItem().toString().equalsIgnoreCase("Sensor 2")) {
//                browser.executeJavaScript("var myLatlng = new google.maps.LatLng(42.349978, -71.080831);\n"
//                        + "var marker = new google.maps.Marker({\n"
//                        + "    position: myLatlng,\n"
//                        + "    map: map,\n"
//                        + "    animation: google.maps.Animation.DROP,\n"
//                        + "    title: 'Poor Air Quality'\n"
//                        + "});");
//            }
//            if (sensorNameJComboBox.getSelectedItem().toString().equalsIgnoreCase("Sensor 3")) {
//                browser.executeJavaScript("var myLatlng = new google.maps.LatLng(42.349213, -71.080576);\n"
//                        + "var marker = new google.maps.Marker({\n"
//                        + "    position: myLatlng,\n"
//                        + "    map: map,\n"
//                        + "    animation: google.maps.Animation.DROP,\n"
//                        + "    title: 'Poor Air Quality'\n"
//                        + "});");
//            }
//        } else if (streetJTextField.getText().equals("Cambridge")) {
//            if (sensorNameJComboBox.getSelectedItem().toString().equalsIgnoreCase("Sensor 1")) {
//                browser.executeJavaScript("var myLatlng = new google.maps.LatLng(42.373616, -71.109734);\n"
//                        + "var marker = new google.maps.Marker({\n"
//                        + "    position: myLatlng,\n"
//                        + "    map: map,\n"
//                        + "    animation: google.maps.Animation.DROP,\n"
//                        + "    title: 'Poor Air Quality'\n"
//                        + "});");
//            }
//            if (sensorNameJComboBox.getSelectedItem().toString().equalsIgnoreCase("Sensor 2")) {
//                browser.executeJavaScript("var myLatlng = new google.maps.LatLng(42.372993, -71.110475);\n"
//                        + "var marker = new google.maps.Marker({\n"
//                        + "    position: myLatlng,\n"
//                        + "    map: map,\n"
//                        + "    animation: google.maps.Animation.DROP,\n"
//                        + "    title: 'Poor Air Quality'\n"
//                        + "});");
//            }
//            if (sensorNameJComboBox.getSelectedItem().toString().equalsIgnoreCase("Sensor 3")) {
//                browser.executeJavaScript("var myLatlng = new google.maps.LatLng(42.374611, -71.107413);\n"
//                        + "var marker = new google.maps.Marker({\n"
//                        + "    position: myLatlng,\n"
//                        + "    map: map,\n"
//                        + "    animation: google.maps.Animation.DROP,\n"
//                        + "    title: 'Poor Air Quality'\n"
//                        + "});");
//            }
//        } else if (streetJTextField.getText().equals("Chinatown")) {
//            if (sensorNameJComboBox.getSelectedItem().toString().equalsIgnoreCase("Sensor 1")) {
//                browser.executeJavaScript("var myLatlng = new google.maps.LatLng(42.350064, -71.062405);\n"
//                        + "var marker = new google.maps.Marker({\n"
//                        + "    position: myLatlng,\n"
//                        + "    map: map,\n"
//                        + "    animation: google.maps.Animation.DROP,\n"
//                        + "    title: 'Poor Air Quality'\n"
//                        + "});");
//            }
//            if (sensorNameJComboBox.getSelectedItem().toString().equalsIgnoreCase("Sensor 2")) {
//                browser.executeJavaScript("var myLatlng = new google.maps.LatLng(42.350952, -71.061854);\n"
//                        + "var marker = new google.maps.Marker({\n"
//                        + "    position: myLatlng,\n"
//                        + "    map: map,\n"
//                        + "    animation: google.maps.Animation.DROP,\n"
//                        + "    title: 'Poor Air Quality'\n"
//                        + "});");
//            }
//            if (sensorNameJComboBox.getSelectedItem().toString().equalsIgnoreCase("Sensor 3")) {
//                browser.executeJavaScript("var myLatlng = new google.maps.LatLng(42.350710, -71.063260);\n"
//                        + "var marker = new google.maps.Marker({\n"
//                        + "    position: myLatlng,\n"
//                        + "    map: map,\n"
//                        + "    animation: google.maps.Animation.DROP,\n"
//                        + "    title: 'Poor Air Quality'\n"
//                        + "});");
//            }
//        } else if (streetJTextField.getText().equals("Downtown")) {
//            if (sensorNameJComboBox.getSelectedItem().toString().equalsIgnoreCase("Sensor 1")) {
//                browser.executeJavaScript("var myLatlng = new google.maps.LatLng(42.355496, -71.059434);\n"
//                        + "var marker = new google.maps.Marker({\n"
//                        + "    position: myLatlng,\n"
//                        + "    map: map,\n"
//                        + "    animation: google.maps.Animation.DROP,\n"
//                        + "    title: 'Poor Air Quality'\n"
//                        + "});");
//            }
//            if (sensorNameJComboBox.getSelectedItem().toString().equalsIgnoreCase("Sensor 2")) {
//                browser.executeJavaScript("var myLatlng = new google.maps.LatLng(42.355955, -71.062560);\n"
//                        + "var marker = new google.maps.Marker({\n"
//                        + "    position: myLatlng,\n"
//                        + "    map: map,\n"
//                        + "    animation: google.maps.Animation.DROP,\n"
//                        + "    title: 'Poor Air Quality'\n"
//                        + "});");
//            }
//            if (sensorNameJComboBox.getSelectedItem().toString().equalsIgnoreCase("Sensor 3")) {
//                browser.executeJavaScript("var myLatlng = new google.maps.LatLng(42.353122, -71.060604);\n"
//                        + "var marker = new google.maps.Marker({\n"
//                        + "    position: myLatlng,\n"
//                        + "    map: map,\n"
//                        + "    animation: google.maps.Animation.DROP,\n"
//                        + "    title: 'Poor Air Quality'\n"
//                        + "});");
//            }
//        } else if (streetJTextField.getText().equals("East-Boston")) {
//            if (sensorNameJComboBox.getSelectedItem().toString().equalsIgnoreCase("Sensor 1")) {
//                browser.executeJavaScript("var myLatlng = new google.maps.LatLng(42.370214, -71.038860);\n"
//                        + "var marker = new google.maps.Marker({\n"
//                        + "    position: myLatlng,\n"
//                        + "    map: map,\n"
//                        + "    animation: google.maps.Animation.DROP,\n"
//                        + "    title: 'Poor Air Quality'\n"
//                        + "});");
//            }
//            if (sensorNameJComboBox.getSelectedItem().toString().equalsIgnoreCase("Sensor 2")) {
//                browser.executeJavaScript("var myLatlng = new google.maps.LatLng(42.369935, -71.037525);\n"
//                        + "var marker = new google.maps.Marker({\n"
//                        + "    position: myLatlng,\n"
//                        + "    map: map,\n"
//                        + "    animation: google.maps.Animation.DROP,\n"
//                        + "    title: 'Poor Air Quality'\n"
//                        + "});");
//            }
//            if (sensorNameJComboBox.getSelectedItem().toString().equalsIgnoreCase("Sensor 3")) {
//                browser.executeJavaScript("var myLatlng = new google.maps.LatLng(42.369455, -71.036703);\n"
//                        + "var marker = new google.maps.Marker({\n"
//                        + "    position: myLatlng,\n"
//                        + "    map: map,\n"
//                        + "    animation: google.maps.Animation.DROP,\n"
//                        + "    title: 'Poor Air Quality'\n"
//                        + "});");
//            }
//        } else if (streetJTextField.getText().equals("Fenway")) {
//            if (sensorNameJComboBox.getSelectedItem().toString().equalsIgnoreCase("Sensor 1")) {
//                browser.executeJavaScript("var myLatlng = new google.maps.LatLng(42.342865, -71.100288);\n"
//                        + "var marker = new google.maps.Marker({\n"
//                        + "    position: myLatlng,\n"
//                        + "    map: map,\n"
//                        + "    animation: google.maps.Animation.DROP,\n"
//                        + "    title: 'Poor Air Quality'\n"
//                        + "});");
//            }
//            if (sensorNameJComboBox.getSelectedItem().toString().equalsIgnoreCase("Sensor 2")) {
//                browser.executeJavaScript("var myLatlng = new google.maps.LatLng(42.342106, -71.099667);\n"
//                        + "var marker = new google.maps.Marker({\n"
//                        + "    position: myLatlng,\n"
//                        + "    map: map,\n"
//                        + "    animation: google.maps.Animation.DROP,\n"
//                        + "    title: 'Poor Air Quality'\n"
//                        + "});");
//            }
//            if (sensorNameJComboBox.getSelectedItem().toString().equalsIgnoreCase("Sensor 3")) {
//                browser.executeJavaScript("var myLatlng = new google.maps.LatLng(42.343348, -71.100508);\n"
//                        + "var marker = new google.maps.Marker({\n"
//                        + "    position: myLatlng,\n"
//                        + "    map: map,\n"
//                        + "    animation: google.maps.Animation.DROP,\n"
//                        + "    title: 'Poor Air Quality'\n"
//                        + "});");
//            }
//        } else if (streetJTextField.getText().equals("Roxbury")) {
//            if (sensorNameJComboBox.getSelectedItem().toString().equalsIgnoreCase("Sensor 1")) {
//                browser.executeJavaScript("var myLatlng = new google.maps.LatLng(42.315198, -71.091375);\n"
//                        + "var marker = new google.maps.Marker({\n"
//                        + "    position: myLatlng,\n"
//                        + "    map: map,\n"
//                        + "    animation: google.maps.Animation.DROP,\n"
//                        + "    title: 'Poor Air Quality'\n"
//                        + "});");
//            }
//            if (sensorNameJComboBox.getSelectedItem().toString().equalsIgnoreCase("Sensor 2")) {
//                browser.executeJavaScript("var myLatlng = new google.maps.LatLng(42.314492, -71.092150);\n"
//                        + "var marker = new google.maps.Marker({\n"
//                        + "    position: myLatlng,\n"
//                        + "    map: map,\n"
//                        + "    animation: google.maps.Animation.DROP,\n"
//                        + "    title: 'Poor Air Quality'\n"
//                        + "});");
//            }
//            if (sensorNameJComboBox.getSelectedItem().toString().equalsIgnoreCase("Sensor 3")) {
//                browser.executeJavaScript("var myLatlng = new google.maps.LatLng(42.316249, -71.091347);\n"
//                        + "var marker = new google.maps.Marker({\n"
//                        + "    position: myLatlng,\n"
//                        + "    map: map,\n"
//                        + "    animation: google.maps.Animation.DROP,\n"
//                        + "    title: 'Poor Air Quality'\n"
//                        + "});");
//            }
//        } else if (streetJTextField.getText().equals("South-Boston")) {
//            if (sensorNameJComboBox.getSelectedItem().toString().equalsIgnoreCase("Sensor 1")) {
//                browser.executeJavaScript("var myLatlng = new google.maps.LatLng(42.338144, -71.047577);\n"
//                        + "var marker = new google.maps.Marker({\n"
//                        + "    position: myLatlng,\n"
//                        + "    map: map,\n"
//                        + "    animation: google.maps.Animation.DROP,\n"
//                        + "    title: 'Poor Air Quality'\n"
//                        + "});");
//            }
//            if (sensorNameJComboBox.getSelectedItem().toString().equalsIgnoreCase("Sensor 2")) {
//                browser.executeJavaScript("var myLatlng = new google.maps.LatLng(42.337265, -71.048483);\n"
//                        + "var marker = new google.maps.Marker({\n"
//                        + "    position: myLatlng,\n"
//                        + "    map: map,\n"
//                        + "    animation: google.maps.Animation.DROP,\n"
//                        + "    title: 'Poor Air Quality'\n"
//                        + "});");
//            }
//            if (sensorNameJComboBox.getSelectedItem().toString().equalsIgnoreCase("Sensor 3")) {
//                browser.executeJavaScript("var myLatlng = new google.maps.LatLng(42.338966, -71.046719);\n"
//                        + "var marker = new google.maps.Marker({\n"
//                        + "    position: myLatlng,\n"
//                        + "    map: map,\n"
//                        + "    animation: google.maps.Animation.DROP,\n"
//                        + "    title: 'Poor Air Quality'\n"
//                        + "});");
//            }
//        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton checkJButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel mapPanel;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton sendLocationJButton;
    private javax.swing.JComboBox sensorNameJComboBox;
    private javax.swing.JTextField streetJTextField;
    // End of variables declaration//GEN-END:variables
}
