/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.LocalOfficial;

import Business.Enterprise.Enterprise;
import Business.Organization.EngineerOrganization;
import Business.Organization.Organization;
import Business.Sensor.Sensor;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.OfficialAirQualityCheckRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Priyank
 */
public class RequestCheckJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Sensor sensor;

    /**
     * Creates new form RequestAirQualityCheck
     */
    public RequestCheckJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, Sensor sensor) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.sensor = sensor;
        streetNameJTextField.setText(userAccount.getStreetLocation().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        streetNameJTextField = new javax.swing.JTextField();
        initiateJButton = new javax.swing.JButton();
        messageJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel3.setText("Request Check");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Street Name");

        streetNameJTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        streetNameJTextField.setEnabled(false);

        initiateJButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        initiateJButton.setText("Initiate");
        initiateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initiateJButtonActionPerformed(evt);
            }
        });

        messageJTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Message");

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(backJButton)
                            .addComponent(jLabel1))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(streetNameJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(messageJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(initiateJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jLabel3)))
                .addContainerGap(308, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(streetNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(initiateJButton)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initiateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initiateJButtonActionPerformed
        boolean flag = false;
        int lastInd = 0;
        if (userAccount.getWorkQueue().getWorkRequestList().isEmpty()) {
            OfficialAirQualityCheckRequest request = new OfficialAirQualityCheckRequest();
            request.setSensor(streetNameJTextField.getText());
            request.setSender(userAccount);
            Date obj = new Date();
            request.setRequestDate(obj);
            request.setStatus("Sent");
            request.setMessage(messageJTextField.getText());
            
            Organization org = null;
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof EngineerOrganization) {
                    org = organization;
                    break;
                }
            }
            
            if (org != null) {
                org.getWorkQueue().getWorkRequestList().add(request);
                userAccount.getWorkQueue().getWorkRequestList().add(request);
            }
            
            JOptionPane.showMessageDialog(null, "Request Initiated.", "Success", JOptionPane.INFORMATION_MESSAGE);
            messageJTextField.setText("");
            
        } else {
            lastInd = userAccount.getWorkQueue().getWorkRequestList().size() - 1;
            WorkRequest request1 = userAccount.getWorkQueue().getWorkRequestList().get(lastInd);
            if (request1.getStatus().equalsIgnoreCase("Sent") || request1.getStatus().equalsIgnoreCase("Pending")) {
                flag = true;
            }
            
            if (flag == false) {
                OfficialAirQualityCheckRequest request = new OfficialAirQualityCheckRequest();
                request.setSensor(streetNameJTextField.getText());
                request.setSender(userAccount);
                Date obj = new Date();
                request.setRequestDate(obj);
                request.setStatus("Sent");
                request.setMessage(messageJTextField.getText());
                
                Organization org = null;
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    if (organization instanceof EngineerOrganization) {
                        org = organization;
                        break;
                    }
                }
                
                if (org != null) {
                    org.getWorkQueue().getWorkRequestList().add(request);
                    userAccount.getWorkQueue().getWorkRequestList().add(request);
                }
                
                JOptionPane.showMessageDialog(null, "Request Initiated.", "Success", JOptionPane.INFORMATION_MESSAGE);
                messageJTextField.setText("");
                
            } else {
                JOptionPane.showMessageDialog(null, "Your previous request is already in progress.", "Error", JOptionPane.ERROR_MESSAGE);
                messageJTextField.setText("");
            }
        }
    }//GEN-LAST:event_initiateJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageWorkRequestJPanel mwr = (ManageWorkRequestJPanel) component;
        mwr.populateRequestTable();
        mwr.populateResidentRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton initiateJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField messageJTextField;
    private javax.swing.JTextField streetNameJTextField;
    // End of variables declaration//GEN-END:variables
}
