/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Resident;

import Business.EcoSystem.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.EngineerOrganization;
import Business.Organization.LocalOfficialOrganization;
import Business.Organization.Organization;
import Business.Organization.ResidentOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.OfficialAirQualityCheckRequest;
import Business.WorkQueue.ResidentAirQualityCheckRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Priyank
 */
public class InitiateRequestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem ecoSystem;

    /**
     * Creates new form InitiateRequestJPanel
     */
    public InitiateRequestJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.ecoSystem = ecoSystem;

        streetJTextField.setText(userAccount.getStreetLocation().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        streetJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        messageJComboBox = new javax.swing.JComboBox();
        intiateJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel3.setText("Initiate Request");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Street Name");

        streetJTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        streetJTextField.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Message");

        messageJComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        messageJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Respiratory Problem", "Health Problem", "Pollution", "Other", " " }));
        messageJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageJComboBoxActionPerformed(evt);
            }
        });

        intiateJButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        intiateJButton.setText("Initiate");
        intiateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intiateJButtonActionPerformed(evt);
            }
        });

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(streetJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(backJButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(intiateJButton))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(42, 42, 42)
                            .addComponent(messageJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(313, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(323, 323, 323))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(streetJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(messageJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(intiateJButton)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void intiateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intiateJButtonActionPerformed
        boolean flag = false;
        int lastInd = 0;
        if (userAccount.getWorkQueue().getWorkRequestList().isEmpty()) {
            ResidentAirQualityCheckRequest request = new ResidentAirQualityCheckRequest();
            request.setMessage(messageJComboBox.getSelectedItem().toString());
            request.setSensor(streetJTextField.getText());
            request.setSender(userAccount);
            Date obj = new Date();
            request.setRequestDate(obj);
            request.setStatus("Sent");

            Organization org1 = null;
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof LocalOfficialOrganization) {
                    org1 = organization;
                    break;
                }
            }

            if (org1 != null) {
                org1.getWorkQueue().getWorkRequestList().add(request);
                userAccount.getWorkQueue().getWorkRequestList().add(request);
            }
            JOptionPane.showMessageDialog(null, "Request initiated", "Success", JOptionPane.INFORMATION_MESSAGE);
        } //            } else {
        //                JOptionPane.showMessageDialog(null, "Your previous request is already in progress.", "Error", JOptionPane.ERROR_MESSAGE);
        //            }
        //        
        //        }
        else {
            lastInd = userAccount.getWorkQueue().getWorkRequestList().size() - 1;
            WorkRequest request1 = userAccount.getWorkQueue().getWorkRequestList().get(lastInd);
            if (request1.getStatus().equalsIgnoreCase("Sent") || request1.getStatus().equalsIgnoreCase("Pending")) {
                flag = true;
            }

            if (flag == false) {
                ResidentAirQualityCheckRequest request = new ResidentAirQualityCheckRequest();
                request.setMessage(messageJComboBox.getSelectedItem().toString());
                request.setSensor(streetJTextField.getText());
                request.setSender(userAccount);
                Date obj = new Date();
                request.setRequestDate(obj);
                request.setStatus("Sent");

                Organization org1 = null;
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    if (organization instanceof LocalOfficialOrganization) {
                        org1 = organization;
                        break;
                    }
                }

                if (org1 != null) {
                    org1.getWorkQueue().getWorkRequestList().add(request);
                    userAccount.getWorkQueue().getWorkRequestList().add(request);
                }
                JOptionPane.showMessageDialog(null, "Request initiated", "Success", JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(null, "Your previous request is already in progress.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_intiateJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        WorkRequestJPanel wr = (WorkRequestJPanel) component;
        wr.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void messageJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageJComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton intiateJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox messageJComboBox;
    private javax.swing.JTextField streetJTextField;
    // End of variables declaration//GEN-END:variables
}
