/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Resident;

import Business.AirQuality.AirIndex;
import Business.EcoSystem.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.ResidentOrganization;
import Business.Sensor.Sensor;
import Business.Street.Street;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Priyank
 */
public class ViewAirQualityJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private ResidentOrganization residentOrganization;
    private Enterprise enterprise;
    private EcoSystem ecoSystem;

    /**
     * Creates new form ViewJPanel
     */
    public ViewAirQualityJPanel(JPanel userProcessContainer, ResidentOrganization residentOrganization, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.residentOrganization = residentOrganization;
        this.enterprise = enterprise;
        this.ecoSystem = ecoSystem;

        stateJTextField.setText("Massachusetts");
        cityJTextField.setText(enterprise.getName());

        populateStreetComboBox();
    }

    public void populateStreetComboBox() {
        streetJComboBox.removeAllItems();
        for (Street street : enterprise.getStreetDirectory().getStreetList()) {
            streetJComboBox.addItem(street);
        }
    }

    public void populateSensorComboBox(Street street) {
        sensorJComboBox.removeAllItems();
        for (Sensor sensor : street.getSensorDirectory().getSensorList()) {
            sensorJComboBox.addItem(sensor);
        }
    }

    public void populateAirIndexTable() {
        DefaultTableModel model = (DefaultTableModel) airIndexJTable.getModel();
        model.setRowCount(0);
        //Street street = (Street) streetJComboBox.getSelectedItem();
        Sensor sensor = (Sensor) sensorJComboBox.getSelectedItem();
        for (AirIndex airIndex : sensor.getAirIndexDirectory().getAirIndexList()) {
            Object[] row = new Object[3];
            row[0] = airIndex.getAirIndex();
            row[1] = airIndex.getTimeStamp();
            row[2] = airIndex.getResult();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        stateJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cityJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        streetJComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        airIndexJTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        sensorJComboBox = new javax.swing.JComboBox();
        getAirIndexJButton = new javax.swing.JButton();

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel3.setText("View Air Quality");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("State");

        stateJTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stateJTextField.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("City");

        cityJTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cityJTextField.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Street");

        streetJComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        streetJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetJComboBoxActionPerformed(evt);
            }
        });

        airIndexJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Air Index", "Time Stamp", "Air Quality"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(airIndexJTable);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Sensor");

        sensorJComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        getAirIndexJButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getAirIndexJButton.setText("Get Air Index");
        getAirIndexJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAirIndexJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(backJButton)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(22, 22, 22)
                                    .addComponent(stateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(streetJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(221, 221, 221)
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(cityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(sensorJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(60, 60, 60)
                                    .addComponent(getAirIndexJButton))))))
                .addGap(141, 141, 141))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(stateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sensorJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(streetJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getAirIndexJButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void getAirIndexJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAirIndexJButtonActionPerformed
        Street street = (Street) streetJComboBox.getSelectedItem();
        if (street.getSensorDirectory().getSensorList().size() == 0) {
            JOptionPane.showMessageDialog(null, "Street's Air Index currently unavailable.", "Sorry", JOptionPane.INFORMATION_MESSAGE);
        } else {
            populateAirIndexTable();
        }
    }//GEN-LAST:event_getAirIndexJButtonActionPerformed

    private void streetJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetJComboBoxActionPerformed
        Street street = (Street) streetJComboBox.getSelectedItem();
        if (street != null) {
            populateSensorComboBox(street);
        }
    }//GEN-LAST:event_streetJComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable airIndexJTable;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField cityJTextField;
    private javax.swing.JButton getAirIndexJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox sensorJComboBox;
    private javax.swing.JTextField stateJTextField;
    private javax.swing.JComboBox streetJComboBox;
    // End of variables declaration//GEN-END:variables
}
