/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Researcher;

import Business.AirQuality.AirIndex;
import Business.EcoSystem.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.ResearchOrganization;
import Business.Sensor.Sensor;
import Business.Street.Street;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.xy.XYDataset;

/**
 *
 * @author Priyank
 */
public class AnalyticsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private ResearchOrganization researchOrganization;
    private EcoSystem ecoSystem;
    private Enterprise enterprise;

    /**
     * Creates new form AnalyticsJPanel
     */
    public AnalyticsJPanel(JPanel userProcessContainer, UserAccount userAccount, ResearchOrganization researchOrganization, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.researchOrganization = researchOrganization;
        this.enterprise = enterprise;
        this.ecoSystem = ecoSystem;

        cityJLabel.setText(enterprise.getName());
        stateJLabel.setText("MA, USA");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        airIndexJButton = new javax.swing.JButton();
        nitrogenJButton = new javax.swing.JButton();
        ozoneJButton = new javax.swing.JButton();
        sulphurJButton = new javax.swing.JButton();
        carbonJButton = new javax.swing.JButton();
        particulateJButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cityJLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        stateJLabel = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel3.setText("Business Analytics");

        airIndexJButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        airIndexJButton.setText("Air Quality Index");
        airIndexJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airIndexJButtonActionPerformed(evt);
            }
        });

        nitrogenJButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nitrogenJButton.setText("Nitogen Dioxide");
        nitrogenJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nitrogenJButtonActionPerformed(evt);
            }
        });

        ozoneJButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ozoneJButton.setText("Ozone");
        ozoneJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ozoneJButtonActionPerformed(evt);
            }
        });

        sulphurJButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sulphurJButton.setText("Sulphur Dioxide");
        sulphurJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sulphurJButtonActionPerformed(evt);
            }
        });

        carbonJButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        carbonJButton.setText("Carbon Monoxide");
        carbonJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carbonJButtonActionPerformed(evt);
            }
        });

        particulateJButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        particulateJButton.setText("Particulate Matter");
        particulateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                particulateJButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel6.setText("City");

        cityJLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        cityJLabel.setText("value");

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel7.setText("State");

        stateJLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        stateJLabel.setText("value");

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(cityJLabel)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(stateJLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(nitrogenJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(particulateJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(airIndexJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(ozoneJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(carbonJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sulphurJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(97, 97, 97))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(cityJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(stateJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(particulateJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airIndexJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nitrogenJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ozoneJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(carbonJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sulphurJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backJButton)
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nitrogenJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nitrogenJButtonActionPerformed
        DefaultCategoryDataset dataSet = new DefaultCategoryDataset();
        //Street street = (Street) streetJComboBox.getSelectedItem();
        ChartFrame frame = null;
        for (Street street : enterprise.getStreetDirectory().getStreetList()) {
            for (Sensor sensor : street.getSensorDirectory().getSensorList()) {
                for (AirIndex airIndex : sensor.getAirIndexDirectory().getAirIndexList()) {
                    dataSet.addValue(airIndex.getNitrogenDioxide(), "Nitrogen Dioxide", airIndex.getTimeStamp());
                }
                JFreeChart chartFactory = ChartFactory.createLineChart3D("AirIndex", "Timestamp", "Value", dataSet, PlotOrientation.VERTICAL, false, true, false);
                CategoryPlot plot = chartFactory.getCategoryPlot();
                plot.setRangeGridlinePaint(Color.blue);
                frame = new ChartFrame("Boston: Nitrogen Dioxide", chartFactory);
            }
        }
        frame.setVisible(true);
        frame.setSize(700, 420);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_nitrogenJButtonActionPerformed

    private void airIndexJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airIndexJButtonActionPerformed
        DefaultCategoryDataset dataSet = new DefaultCategoryDataset();
        //Street street = (Street) streetJComboBox.getSelectedItem();
        ChartFrame frame = null;
        for (Street street : enterprise.getStreetDirectory().getStreetList()) {
            for (Sensor sensor : street.getSensorDirectory().getSensorList()) {
                for (AirIndex airIndex : sensor.getAirIndexDirectory().getAirIndexList()) {
                    dataSet.addValue(airIndex.getAirIndex(), "Air Index", airIndex.getTimeStamp());
                }
                JFreeChart chartFactory = ChartFactory.createStackedBarChart3D("AirIndex", "Timestamp", "Value", dataSet, PlotOrientation.VERTICAL, false, true, false);
                CategoryPlot plot = chartFactory.getCategoryPlot();
                plot.setRangeGridlinePaint(Color.blue);
                frame = new ChartFrame("Boston: Air Index", chartFactory);
            }
        }
        frame.setVisible(true);
        frame.setSize(700, 420);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_airIndexJButtonActionPerformed

    private void sulphurJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sulphurJButtonActionPerformed
        DefaultCategoryDataset dataSet = new DefaultCategoryDataset();
        //Street street = (Street) streetJComboBox.getSelectedItem();
        ChartFrame frame = null;
        for (Street street : enterprise.getStreetDirectory().getStreetList()) {
            for (Sensor sensor : street.getSensorDirectory().getSensorList()) {
                for (AirIndex airIndex : sensor.getAirIndexDirectory().getAirIndexList()) {
                    dataSet.addValue(airIndex.getSulphurDioxide(), "Sulphur Dioxide", airIndex.getTimeStamp());
                }
                JFreeChart chartFactory = ChartFactory.createLineChart3D("AirIndex", "Timestamp", "Value", dataSet, PlotOrientation.VERTICAL, false, true, false);
                CategoryPlot plot = chartFactory.getCategoryPlot();
                plot.setRangeGridlinePaint(Color.blue);
                frame = new ChartFrame("Boston: Sulphur Dioxide", chartFactory);
            }
        }
        frame.setVisible(true);
        frame.setSize(700, 420);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_sulphurJButtonActionPerformed

    private void carbonJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carbonJButtonActionPerformed
        DefaultCategoryDataset dataSet = new DefaultCategoryDataset();
        //Street street = (Street) streetJComboBox.getSelectedItem();
        ChartFrame frame = null;
        for (Street street : enterprise.getStreetDirectory().getStreetList()) {
            for (Sensor sensor : street.getSensorDirectory().getSensorList()) {
                for (AirIndex airIndex : sensor.getAirIndexDirectory().getAirIndexList()) {
                    dataSet.addValue(airIndex.getCarbonMonoxide(), "Carbon Monoxide", airIndex.getTimeStamp());
                }
                JFreeChart chartFactory = ChartFactory.createLineChart3D("AirIndex", "Timestamp", "Value", dataSet, PlotOrientation.VERTICAL, false, true, false);
                CategoryPlot plot = chartFactory.getCategoryPlot();
                plot.setRangeGridlinePaint(Color.blue);
                frame = new ChartFrame("Boston: Carbon Monoxide", chartFactory);
            }
        }
        frame.setVisible(true);
        frame.setSize(700, 420);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_carbonJButtonActionPerformed

    private void ozoneJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ozoneJButtonActionPerformed
        DefaultCategoryDataset dataSet = new DefaultCategoryDataset();
        //Street street = (Street) streetJComboBox.getSelectedItem();
        ChartFrame frame = null;
        for (Street street : enterprise.getStreetDirectory().getStreetList()) {
            for (Sensor sensor : street.getSensorDirectory().getSensorList()) {
                for (AirIndex airIndex : sensor.getAirIndexDirectory().getAirIndexList()) {
                    dataSet.addValue(airIndex.getOzone(), "Ozone", airIndex.getTimeStamp());
                }
                JFreeChart chartFactory = ChartFactory.createLineChart3D("AirIndex", "Timestamp", "Value", dataSet, PlotOrientation.VERTICAL, false, true, false);
                CategoryPlot plot = chartFactory.getCategoryPlot();
                plot.setRangeGridlinePaint(Color.blue);
                frame = new ChartFrame("Boston: Ozone", chartFactory);
            }
        }
        frame.setVisible(true);
        frame.setSize(700, 420);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_ozoneJButtonActionPerformed

    private void particulateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_particulateJButtonActionPerformed
        DefaultCategoryDataset dataSet = new DefaultCategoryDataset();
        //Street street = (Street) streetJComboBox.getSelectedItem();
        ChartFrame frame = null;
        for (Street street : enterprise.getStreetDirectory().getStreetList()) {
            for (Sensor sensor : street.getSensorDirectory().getSensorList()) {
                for (AirIndex airIndex : sensor.getAirIndexDirectory().getAirIndexList()) {
                    dataSet.addValue(airIndex.getParticulateMatter(), "Particulate Matter", airIndex.getTimeStamp());
                }
                JFreeChart chartFactory = ChartFactory.createLineChart3D("AirIndex", "Timestamp", "Value", dataSet, PlotOrientation.VERTICAL, false, true, false);
                CategoryPlot plot = chartFactory.getCategoryPlot();
                plot.setRangeGridlinePaint(Color.blue);
                frame = new ChartFrame("Boston: Particulate Matter", chartFactory);
            }
        }
        frame.setVisible(true);
        frame.setSize(700, 420);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_particulateJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton airIndexJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton carbonJButton;
    private javax.swing.JLabel cityJLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton nitrogenJButton;
    private javax.swing.JButton ozoneJButton;
    private javax.swing.JButton particulateJButton;
    private javax.swing.JLabel stateJLabel;
    private javax.swing.JButton sulphurJButton;
    // End of variables declaration//GEN-END:variables
}
