/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Researcher;

import Business.EcoSystem.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.ResearchOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Priyank
 */
public class ResearcherWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private ResearchOrganization researchOrganization;
    private Enterprise enterprise;
    private EcoSystem ecoSystem;

    /**
     * Creates new form ResearcherWorkAreaJPanel
     */
    public ResearcherWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, ResearchOrganization researchOrganization, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.researchOrganization = researchOrganization;
        this.enterprise = enterprise;
        this.ecoSystem = ecoSystem;

        researchJLabel.setText(userAccount.getEmployee().getEmployeeName());
        streetJLabel.setText(userAccount.getStreetLocation().getStreetName());
        cityJLabel.setText(enterprise.getName());
        stateJLabel.setText("MA, USA");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        requestDataJButton = new javax.swing.JButton();
        checkAnalyticsJButton = new javax.swing.JButton();
        checkStatisticsJButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        streetJLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        researchJLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cityJLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        stateJLabel = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel3.setText("Research Work Area");

        requestDataJButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        requestDataJButton.setText("Request Data");
        requestDataJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestDataJButtonActionPerformed(evt);
            }
        });

        checkAnalyticsJButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkAnalyticsJButton.setText("Check Analytics");
        checkAnalyticsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAnalyticsJButtonActionPerformed(evt);
            }
        });

        checkStatisticsJButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkStatisticsJButton.setText("Check Statistics");
        checkStatisticsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkStatisticsJButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel5.setText("Street");

        streetJLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        streetJLabel.setText("value");

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel4.setText("Welcome");

        researchJLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        researchJLabel.setText("value");

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel6.setText("City");

        cityJLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        cityJLabel.setText("value");

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel7.setText("State");

        stateJLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        stateJLabel.setText("value");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkAnalyticsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requestDataJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkStatisticsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(338, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(streetJLabel)
                    .addComponent(researchJLabel))
                .addGap(118, 118, 118)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cityJLabel)
                    .addComponent(stateJLabel))
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(researchJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(streetJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cityJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stateJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGap(9, 9, 9)
                .addComponent(requestDataJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkAnalyticsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkStatisticsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestDataJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestDataJButtonActionPerformed
        RequestDataJPanel requestDataJPanel = new RequestDataJPanel(userProcessContainer, userAccount, researchOrganization, enterprise, ecoSystem);
        userProcessContainer.add("RequestDataJPanel", requestDataJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_requestDataJButtonActionPerformed

    private void checkAnalyticsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAnalyticsJButtonActionPerformed
        boolean flag = false;
        int lastInd = 0;
        if (userAccount.getWorkQueue().getWorkRequestList().size() > 0) {
            lastInd = userAccount.getWorkQueue().getWorkRequestList().size() - 1;

            WorkRequest request = userAccount.getWorkQueue().getWorkRequestList().get(lastInd);
            if (request.getStatus().equalsIgnoreCase("Completed")) {
                flag = true;
            }

            if (flag == true) {
                AnalyticsJPanel analyticsJPanel = new AnalyticsJPanel(userProcessContainer, userAccount, researchOrganization, enterprise, ecoSystem);
                userProcessContainer.add("AnalyicsJPanel", analyticsJPanel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            } else {
                JOptionPane.showMessageDialog(null, "You don't have the permission to access Analytical information.", "Sorry", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "You don't have the permission to access Analytical information.", "Sorry", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_checkAnalyticsJButtonActionPerformed

    private void checkStatisticsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkStatisticsJButtonActionPerformed
        boolean flag = false;
        int lastInd = 0;
        if (userAccount.getWorkQueue().getWorkRequestList().size() > 0) {
            lastInd = userAccount.getWorkQueue().getWorkRequestList().size() - 1;

            WorkRequest request = userAccount.getWorkQueue().getWorkRequestList().get(lastInd);
            if (request.getStatus().equalsIgnoreCase("Completed")) {
                flag = true;
            }

            if (flag == true) {
                StatisticsJPanel statisticsJPanel = new StatisticsJPanel(userProcessContainer, userAccount, researchOrganization, enterprise, ecoSystem);
                userProcessContainer.add("StatisticsJPanel", statisticsJPanel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            } else {
                JOptionPane.showMessageDialog(null, "You don't have the permission to access Analytical information.", "Sorry", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "You don't have the permission to access Analytical information.", "Sorry", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_checkStatisticsJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkAnalyticsJButton;
    private javax.swing.JButton checkStatisticsJButton;
    private javax.swing.JLabel cityJLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton requestDataJButton;
    private javax.swing.JLabel researchJLabel;
    private javax.swing.JLabel stateJLabel;
    private javax.swing.JLabel streetJLabel;
    // End of variables declaration//GEN-END:variables
}
