/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Researcher;

import Business.AirQuality.AirIndex;
import Business.EcoSystem.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.ResearchOrganization;
import Business.Sensor.Sensor;
import Business.Street.Street;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Priyank
 */
public class StatisticsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private ResearchOrganization researchOrganization;
    private EcoSystem ecoSystem;
    private Enterprise enterprise;

    /**
     * Creates new form StatisticsJPanel
     */
    public StatisticsJPanel(JPanel userProcessContainer, UserAccount userAccount, ResearchOrganization researchOrganization, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.researchOrganization = researchOrganization;
        this.enterprise = enterprise;
        this.ecoSystem = ecoSystem;

        cityJLabel.setText(enterprise.getName());
        stateJLabel.setText("MA, USA");

        for (Street street : enterprise.getStreetDirectory().getStreetList()) {
            streetJComboBox.addItem(street);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cityJLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        stateJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        statisticsJTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();
        streetJComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        getStatisticsJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        cityJLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        cityJLabel.setText("value");

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel6.setText("City");

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel3.setText("Business Statistics");

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel7.setText("State");

        stateJLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        stateJLabel.setText("value");

        statisticsJTable.setAutoCreateRowSorter(true);
        statisticsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Result", "Air Index", "Nitrogen Dioxide", "Sulphur Dioxide", "Carbon Monoxide", "Ozone", "Particulate Matter"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(statisticsJTable);

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Street");

        getStatisticsJButton.setText("Get Statistics");
        getStatisticsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getStatisticsJButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel4.setText("Best & Worst Results");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(streetJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(getStatisticsJButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(cityJLabel)
                                        .addGap(146, 146, 146)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(242, 242, 242)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(stateJLabel)))
                        .addGap(99, 99, 99))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(cityJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(stateJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(streetJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(getStatisticsJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backJButton)
                .addContainerGap(161, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void getStatisticsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getStatisticsJButtonActionPerformed
        Street street = (Street) streetJComboBox.getSelectedItem();
        if (street.getSensorDirectory().getSensorList().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Street statistics currently unavailable.", "Error", JOptionPane.ERROR_MESSAGE);
            populateEmptyTable();
        } else {
            populateStatisticsTable();
        }
    }//GEN-LAST:event_getStatisticsJButtonActionPerformed
    public void populateEmptyTable() {
        DefaultTableModel dtm = (DefaultTableModel) statisticsJTable.getModel();
        dtm.setRowCount(0);
    }

    public void populateStatisticsTable() {
        DefaultTableModel dtm = (DefaultTableModel) statisticsJTable.getModel();
        dtm.setRowCount(0);
        HashMap<Object, ArrayList<Integer>> customerMap = new HashMap<Object, ArrayList<Integer>>();
        for (Street street : enterprise.getStreetDirectory().getStreetList()) {
            for (Sensor sensor : street.getSensorDirectory().getSensorList()) {
                for (AirIndex airIndex : sensor.getAirIndexDirectory().getAirIndexList()) {
                    Object row[] = new Object[7];
                    row[0] = airIndex;
                    row[1] = (int) airIndex.getAirIndex();
                    row[2] = (int) airIndex.getNitrogenDioxide();
                    row[3] = (int) airIndex.getSulphurDioxide();
                    row[4] = (int) airIndex.getCarbonMonoxide();
                    row[5] = (int) airIndex.getOzone();
                    row[6] = (int) airIndex.getParticulateMatter();
                    ArrayList<Integer> intArr = new ArrayList<>();
                    intArr.add((int)row[1]);
                    intArr.add((int)row[2]);
                    intArr.add((int)row[3]);
                    intArr.add((int)row[4]);
                    intArr.add((int)row[5]);
                    intArr.add((int)row[6]);
                    
                    if (!customerMap.containsKey(row[0])) {
                        customerMap.put(row[0], intArr);
                    } else {
                        customerMap.put(row[0], intArr);
                    }
                }
            }
        }
        for (Map.Entry<Object, ArrayList<Integer>> entry : customerMap.entrySet()) {
            Object row[] = new Object[7];
            row[0] = entry.getKey();
            int ind=1;
            for(Integer i:entry.getValue()){
                
                row[ind] = i;
                ind++;
            }
            
            dtm.addRow(row);
        }
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<DefaultTableModel>(dtm);
        statisticsJTable.setRowSorter(sorter);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel cityJLabel;
    private javax.swing.JButton getStatisticsJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel stateJLabel;
    private javax.swing.JTable statisticsJTable;
    private javax.swing.JComboBox streetJComboBox;
    // End of variables declaration//GEN-END:variables
}
